# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60dc5bdfde969f9f0e468123f208578abc530b152f2e0e4ede049fdd259a2ae8ffb1d53c4560f0e040c53a7d8dce358b1250b496db2e05a0d02e8176ae56786d

test:
  secret_key_base: ed3f235b060ef19faccf01900d7c148e6619700055dfcd798c957e147f2a2d46d920c28bcb3631410883174e2be74f58938d2f3606d91fc9337c397d1a7d61c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
